### ISSUE TITLE
2022 10 18 - Green Software Principles Agenda & Minutes

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#100]
## Date
2022-10-18 - 1.30pm UTC (meeting to be run by Asim / Sarah)

## Agenda / Updates
- Anita: following up with the LF to make sure we can all start testing the course next week. 
- Asim & Osama: should start working on the landing page as soon as their priorities allow.
- Re: COP, there will be a dry run on November 2. Sean will reach out to Sarah & Bill to confirm the details.
- Code freeze still in progress, no new issues at the time of creating this agenda. 
- Added one PR today https://github.com/Green-Software-Foundation/training/pull/99

## Decisions / Discussions
to be added, if any

## In progress
- [ ] (Anita, due by Nov 2) https://github.com/Green-Software-Foundation/training/issues/94

## Pending Items 
- [ ] (Asim/Osama) https://github.com/Green-Software-Foundation/training/issues/89
- [ ] (Team, next week) https://github.com/Green-Software-Foundation/training/issues/84
- [ ] (Team, next week) https://github.com/Green-Software-Foundation/training/issues/96
- [ ] (Sarah, Nov 10) https://github.com/Green-Software-Foundation/training/issues/97
- [ ] (TBD, after COP) https://github.com/Green-Software-Foundation/training/issues/95
- [ ] (Asim/Osama) Add a "Get Certified" button on our website which points to the training as per Sarah's suggestion
- [ ] (Asim/Osama) Redirect Principles.green to new website as it still gets a decent amount of traffic
- [ ] (Asim/Osama) Share Github stats and list of active contributors 
- [ ] (Asim/Osama) Tidy up list of contributors on the website
- [ ] (Asim/Tammy) Education WG (workshops, content, university level groups / MSLA, student ambassador programs, etc.)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees (updated based on comments)
**Asim H., Cameron C., Markus S., Navveen B., Sarah H.**

**Comment by markus-ntt-seidl** [comment]
Attended

**Comment by jawache** [comment]
From Naveem:
1. explore legal implications, especially when we have regulatory norms like GDPR
2. explore SSO integration with the Linux Foundation Learning Platform

**Comment by navveenb** [comment]
Attended

**Comment by camcash17** [comment]
Attended

**Comment by greenhsu123** [comment]
attended.

**Comment by holanita** [comment]
List of attendees updated based on comments, notes from Navveen added to [next agenda](https://github.com/Green-Software-Foundation/training/issues/102).
