### ISSUE TITLE
2022 10 11 - Green Software Principles Agenda & Minutes

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#98]
## Date
2022-10-11 - 1.30pm UTC (meeting to be run by Asim and/or Bill)

## Agenda
Code freeze started last week. There are no immediate action items for the team right now. Anita is working with the LF on setting up the course. Asim & Osama should start working on the landing page as soon as priorities allow.

- [ ] Review new issues or PRs, if any
- [ ] Review new comments, if any - https://github.com/Green-Software-Foundation/training/issues/85

## Decisions / Discussions
to be added, if any

## Next Steps
- [ ] asap - Anita to follow up with the LF on https://github.com/Green-Software-Foundation/training/issues/94
- [ ] asap - Asim & Osama to start working on https://github.com/Green-Software-Foundation/training/issues/89
- [ ] End of October - https://github.com/Green-Software-Foundation/training/issues/84
- [ ] End of October  - https://github.com/Green-Software-Foundation/training/issues/96
- [ ] November 2 - finalize https://github.com/Green-Software-Foundation/training/issues/94
- [ ] November 11 - Sarah to https://github.com/Green-Software-Foundation/training/issues/97
- [ ] After COP - start https://github.com/Green-Software-Foundation/training/issues/95

## Pending Items 
- [ ] (Asim/Osama) Add a "Get Certified" button on our website which points to the training as per Sarah's suggestion
- [ ] (Asim/Osama) Redirect Principles.green to new website as it still gets a decent amount of traffic
- [ ] (Asim/Osama) Share Github stats and list of active contributors 
- [ ] (Asim/Osama) Tidy up list of contributors on the website
- [ ] (Asim/Tammy) Education WG (workshops, content, university level groups / MSLA, student ambassador programs, etc.)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees 
to be updated after the meeting
**Akshit B., Aoife F., Asim H., Bill. J., Markus S., Navveen B., Sarah H., Tammy M.**
